import React from 'react';
import { UserProfile } from '../../lib/types';
import { QuizIcon, ObjectsIcon, StoryIcon, StarIcon, LightbulbIcon, TreasureHuntIcon, ScienceIcon } from '../Icons/Icons';
import { LoadingView } from '../LoadingView/LoadingView';
import './StaticPages.css';

type StaticPageProps = {
  t: (key: string) => string;
};

export const AboutUsScreen = ({ t }: StaticPageProps) => (
    <div className="static-page-view">
        <h2>Welcome to KidEd!</h2>
        <p>Our mission is to make learning a joyful and interactive adventure for kids aged 4-8. We believe that curiosity is the best teacher, and with a little help from our friendly AI, we can unlock a world of discovery for your child.</p>
        
        <h3>Our Amazing Features:</h3>
        
        <h4>Object Detective</h4>
        <p>Ever wonder what something is? Just point your camera at it! Our AI buddy will instantly identify objects, animals, or places and share amazing fun facts. It's like having a magical magnifying glass that knows everything!</p>

        <h4>Interactive Story Time</h4>
        <p>Become the hero of your own adventure! We'll start a story, and you get to make the choices that decide what happens next. The best part? The heroes of the story can be the very objects you've discovered and collected in your sticker book!</p>

        <h4>Fun Quiz</h4>
        <p>Challenge yourself with an endless stream of fun quiz questions. As you play more, you'll level up, and the questions will grow with you, keeping things exciting and new.</p>

        <h4>Digital Sticker Book</h4>
        <p>For every new object you discover with the Object Detective, you'll earn a beautiful, custom-designed sticker for your collection. Fill your book with all the amazing things you've learned about!</p>
    </div>
);

export const TermsScreen = ({ t }: StaticPageProps) => (
    <div className="static-page-view">
        <h2>Terms & Conditions</h2>
        <p>Welcome to KidEd. By using our application, you agree to these terms. Please read them carefully.</p>
        
        <h4>1. Use of Service</h4>
        <p>KidEd is provided for educational and entertainment purposes for children. The content is generated by AI and should be used under parental guidance. You agree to use the app responsibly and not for any unlawful purpose.</p>

        <h4>2. Privacy</h4>
        <p>Your privacy is important to us. Our Privacy Policy explains how we collect, use, and protect your information. We do not knowingly collect personal information from children without parental consent.</p>

        <h4>3. Intellectual Property</h4>
        <p>All content within KidEd, including the design, text, graphics, and AI-generated content, is the property of KidEd and is protected by copyright laws.</p>
    </div>
);

export const PrivacyScreen = ({ t }: StaticPageProps) => (
    <div className="static-page-view">
        <h2>Privacy Policy</h2>
        <p>Last updated: [Date]</p>
        <p>KidEd is committed to protecting the privacy of our young users and their families.</p>
        
        <h4>Information We Collect</h4>
        <p>We do not require users to create an account. We may collect non-personal data such as device type and usage statistics to improve the app experience. Images and voice data processed for features like Object Detective and voice commands are processed in real-time and are not stored on our servers.</p>

        <h4>How We Use Information</h4>
        <p>The data we collect is used solely for the purpose of operating and improving the KidEd application. We do not sell or share any data with third parties for marketing purposes.</p>

        <h4>Parental Controls</h4>
        <p>We encourage parents to supervise their children's use of the app. You can manage permissions for the camera and microphone through your device's settings.</p>
    </div>
);


const activityIcons: { [key: string]: JSX.Element } = {
  'quiz': <QuizIcon />,
  'object-scan': <ObjectsIcon />,
  'story': <StoryIcon />,
  'treasure-hunt': <TreasureHuntIcon />,
  'learning-camp': <ScienceIcon />,
  'default': <StarIcon filled />,
};

type ParentDashboardProps = {
    profile: UserProfile | null;
    tips: string;
    isLoadingTips: boolean;
    t: (key: string) => string;
}
export const ParentDashboardView = ({ profile, tips, isLoadingTips, t }: ParentDashboardProps) => {
    const formatTimestamp = (isoString: string) => {
        return new Date(isoString).toLocaleString(undefined, {
            dateStyle: 'medium',
            timeStyle: 'short'
        });
    };

    return (
        <div className="parent-dashboard-view">
            <h2>{t('parentDashboard.title')}</h2>
            <p>{t('parentDashboard.description').replace('{name}', profile?.name || 'your child')}</p>

            <div className="dashboard-section">
                <h3><StarIcon filled /> {t('parentDashboard.timelineHeader')}</h3>
                {profile?.activityLog && profile.activityLog.length > 0 ? (
                    <ul className="timeline">
                        {profile.activityLog.map(log => (
                            <li key={log.id} className="timeline-item">
                                <div className="timeline-icon">
                                    {activityIcons[log.type] || activityIcons['default']}
                                </div>
                                <div className="timeline-content">
                                    <h4>{log.description}</h4>
                                    <p className="timestamp">{formatTimestamp(log.timestamp)}</p>
                                </div>
                            </li>
                        ))}
                    </ul>
                ) : (
                    <p className="empty-timeline">{t('parentDashboard.emptyTimeline')}</p>
                )}
            </div>
            
            <div className="dashboard-section">
                <h3><LightbulbIcon /> {t('parentDashboard.tipsHeader')}</h3>
                {isLoadingTips ? (
                    <LoadingView t={t} />
                ) : (
                    <div className="tips-content" dangerouslySetInnerHTML={{ __html: tips.replace(/\*/g, '').replace(/\n/g, '<br />') }} />
                )}
            </div>
        </div>
    );
};

// FIX: This structure was causing issues with React.lazy.
// It's better to have a default export that is a component.
const StaticPages: React.FC & {
    AboutUsScreen: typeof AboutUsScreen;
    TermsScreen: typeof TermsScreen;
    PrivacyScreen: typeof PrivacyScreen;
    ParentDashboardView: typeof ParentDashboardView;
// A dummy component that holds the actual components as properties.
} = () => null;

StaticPages.AboutUsScreen = AboutUsScreen;
StaticPages.TermsScreen = TermsScreen;
StaticPages.PrivacyScreen = PrivacyScreen;
StaticPages.ParentDashboardView = ParentDashboardView;

export default StaticPages;
